# Site settings
title: 心内求法 
email: wanghaikuo@tsinghua.org.cn
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://holbrook.github.io" # the base hostname & protocol for your site

# Build settings
markdown:       rdiscount
safe:           true
lsi:            false
highlighter:    pygments
permalink:      /:year/:month/:day/:title.html
author:		Holbrook(wanghaikuo@gmail.com)
feed:           /atom.xml
paginate:       20
paginate_path: "/:num"

menuitems:
    - title:     首页
      url:      /index.html
    - title:     分类 
      url:      /categories.html
    - title:     归档
      url:      /pages/archives.html
    - title:     标签
      url:      /pages/tags.html
    - title:     关于
      url:      /pages/about.html
